### ISSUE TITLE
[Umberlla] Issues with undo

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-undo#65]
Since we know that there a lot of issues with undo found after the recent refactoring let's report them in one place.

**Comment by Reinmar** [comment]
Selection is restored incorrectly:

![jul-06-2017 18-11-20](https://user-images.githubusercontent.com/156149/27920963-93ee67e0-6276-11e7-9e27-e8934399dfc6.gif)

**Comment by Reinmar** [comment]
Rename leaks to a nearby element.

![jul-06-2017 18-14-28](https://user-images.githubusercontent.com/156149/27921106-fafd5446-6276-11e7-9441-6e6053085978.gif)

**Comment by Reinmar** [comment]
Undo becomes noticeably slow when undoing typing :((((

It seems that typing compression will be a must-have in a short time.

![jul-06-2017 18-19-31](https://user-images.githubusercontent.com/156149/27921348-c5d3caba-6277-11e7-9d10-b5a8ee03e5ba.gif)

**Comment by Reinmar** [comment]
![jul-06-2017 18-23-14](https://user-images.githubusercontent.com/156149/27921483-36c9497a-6278-11e7-950d-2bb858519f6b.gif)

```
basic-transformations.js:67 Uncaught TypeError: Cannot read property 'getNode' of undefined
    at addTransformationCase (basic-transformations.js:67)
    at Object.transform (transform.js:59)
    at Object.transformDeltaSets (transform.js:268)
    at Document.transformDeltas (document.js:359)
    at RedoCommand._undo (basecommand.js:140)
    at Array.editor.document.enqueueChanges (redocommand.js:42)
    at Document.enqueueChanges (document.js:241)
    at RedoCommand.execute (redocommand.js:36)
    at RedoCommand.on (observablemixin.js:327)
    at RedoCommand.fire (emittermixin.js:281)
```

**Comment by scofalik** [comment]
> Undo becomes noticeably slow when undoing typing :((((

Yes... This was another gain that we had when removing stuff from history. There was much less transformations. I am sure we will spend time on this subject because it cannot work like this. I think there are places where optimisation could be applied, but this needs to be measured and researched.

Later, we can think about some tricks to maybe somehow skip some transformations or something but this has to be:
1. Done when 99% of cases work (meaning that we solved all issues we know about).
2. Done very carefully so we won't fall again into some kind of trap like with `History`.

**Comment by Reinmar** [comment]
![jul-07-2017 10-16-09](https://user-images.githubusercontent.com/156149/27949290-71d530d0-62fd-11e7-84d2-9039c0175bb4.gif)

```
position.js:158 Uncaught TypeError: this.parent.offsetToIndex is not a function
    at Position.get index [as index] (position.js:158)
    at Position.get textNode [as textNode] (position.js:169)
    at Position.get nodeAfter [as nodeAfter] (position.js:181)
    at _fixItemsIndent (converters.js:629)
    at Document.<anonymous> (converters.js:576)
    at Document.fire (emittermixin.js:281)
    at Document.applyOperation (document.js:173)
    at UndoCommand._undo (basecommand.js:153)
    at Array.editor.document.enqueueChanges (undocommand.js:40)
    at Document.enqueueChanges (document.js:241)
```

**Comment by Reinmar** [comment]
As for performance issues. I did a quick check.

Here's a general overview of a single undo step:

![image](https://user-images.githubusercontent.com/156149/27957804-5233262e-6320-11e7-8199-dff206c5c4fe.png)

20 `transformDeltas()` calls. Each 10ms. But the further you go back in the undo history, the longer the `transformDeltas()` calls.

Now, it's very interesting to see what are the widest leafs of this flame chart:

![image](https://user-images.githubusercontent.com/156149/27957781-3d9318d2-6320-11e7-905a-c3d9477c05b4.png)

Yep, `Position()` constructors. If you'll scroll more you'll see that there also other constructors there (and they are similarly long), but the problem is that `Position` repeats hundreds of times.

So, it's very likely that one of the most important issues https://github.com/ckeditor/ckeditor5-engine/issues/897.

**Comment by Reinmar** [comment]
![jul-10-2017 21-50-55](https://user-images.githubusercontent.com/156149/28036881-ed4c338a-65b9-11e7-9306-415196981e00.gif)

* Enter
* Bold
* Forward delete (backspace or fn+delete on macOS)
* Undo

```
ckeditorerror.js:38 Uncaught CKEditorError: model-history-wrong-version: Given base version points to the middle of a delta.
    at History._getIndex (http://localhost:8125/ckeditor5-presets/tests/manual/article.js:41285:10)
    at History.getDeltas (http://localhost:8125/ckeditor5-presets/tests/manual/article.js:41187:24)
    at getDeltas.next (<anonymous>)
    at Function.from (native)
    at UndoCommand._undo (http://localhost:8125/ckeditor5-presets/tests/manual/article.js:29872:32)
    at Array.editor.document.enqueueChanges (http://localhost:8125/ckeditor5-presets/tests/manual/article.js:47229:30)
    at Document.enqueueChanges (http://localhost:8125/ckeditor5-presets/tests/manual/article.js:40085:30)
    at UndoCommand.execute (http://localhost:8125/ckeditor5-presets/tests/manual/article.js:47228:24)
    at UndoCommand.on (http://localhost:8125/ckeditor5-presets/tests/manual/article.js:5973:32)
    at UndoCommand.fire (http://localhost:8125/ckeditor5-presets/tests/manual/article.js:4267:29)
```

**Comment by Reinmar** [comment]
**This is not a regression** but it's a bug worth checking anyway.

![jul-13-2017 18-04-06](https://user-images.githubusercontent.com/156149/28175857-bb66c630-67f5-11e7-8c7f-e289f5d069ee.gif)

**Comment by scofalik** [comment]
The above might be one of "cannot fix with how converters work now" bug. There are actually 6 tests in integration of undo with lists that are intentionally skipped because they are failing. These are the cases that cannot be (at least easily) solved with current state of how conversion works. We skipped them to deliver Nested Lists feature faster.

If we change conversion to happen on `changesDone` those cases will be probably easier to solve and then we can get back to them.

**Comment by Mgsy** [comment]
## Steps to reproduce
1. Load the clipboard plugin to the markers test.
2. Go to http://localhost:8125/ckeditor5-engine/tests/manual/markers.html
3. Create 2 lines of text.
4. Select them and press <kbd>Ctrl</kbd> + <kbd>C</kbd>.
5. Put the caret inside the marker.
6. Press <kbd>Ctrl</kbd> + <kbd>V</kbd>.
7. Press <kbd>Ctrl</kbd> + <kbd>Z</kbd>.

## Current result
- Some part of the marker and text is lost
- There is the error in the console

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/28266226-06db0dd2-6af4-11e7-864b-824107855032.gif)

## Error
```
position.js:221 Uncaught TypeError: Cannot read property 'root' of undefined
    at Position.compareWith (position.js:221)
    at Position.isEqual (position.js:411)
    at addTransformationCase (basic-transformations.js:396)
    at Object.transform (transform.js:59)
    at Object.transformDeltaSets (transform.js:261)
    at Document.transformDeltas (document.js:359)
    at UndoCommand._undo (basecommand.js:140)
    at Array.editor.document.enqueueChanges (undocommand.js:40)
    at Document.enqueueChanges (document.js:241)
    at UndoCommand.execute (undocommand.js:39)
```

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Edge, Firefox, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
1. Copy all.
2. Paste at the end of the content.
3. Undo.

![aug-09-2017 10-30-51](https://user-images.githubusercontent.com/156149/29112340-ddce65c2-7ced-11e7-9720-6c8e4024dcc7.gif)

**Comment by Mgsy** [comment]
## Steps to reproduce
1. Put the caret at the beginning of the paragraph.
2. Press <kbd>Enter</kbd>.
3. Press <kbd>Ctrl</kbd> + <kbd>Z</kbd>.

## Current result
The caret was moved to the end of the paragraph.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/29120996-f8041878-7d0c-11e7-8f1d-44f3d748a103.gif)

**Comment by scofalik** [comment]
Selection restoring doesn't work correctly, we know about it and will change it, hopefully soon.

**Comment by scofalik** [comment]
After I fixed this issue: https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-321190168 I noticed that undo+redo creates different content than it was at the beginning. It's worth to check why it happens. It fails even for fairly non-complicated copy paste. It has to be checked whether there is a bug in: copy/paste, OT or converters and whether this happens only for content with lists or also in other cases.

![aug-10-2017 10-12-09](https://user-images.githubusercontent.com/1502228/29160890-58c720ea-7db4-11e7-99e8-d1852976f5a3.gif)

**Comment by Mgsy** [comment]
Quote block is removed after undo/redo operations.

## Steps to reproduce
1. Create new paragraph and new quote block.
2. Put the caret at the end of the paragraph.
3. Press <kbd>Delete</kbd>.
4. Press <kbd>Ctrl</kbd> + <kbd>Z</kbd>.
5. <kbd>Ctrl</kbd> + <kbd>Y</kbd>.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/29356801-ba00c63e-8275-11e7-8833-eb5ad0111b87.gif)

**Comment by Mgsy** [comment]
Block element was removed after undo.

## Steps to reproduce
1. Create two block elements, i.e. paragraphs.
2. Put the caret at the end of the first paragraph.
3. Press <kbd>Enter</kbd>.
4. Press <kbd>Delete</kbd>.
5. Press <kbd>Ctrl</kbd> + <kbd>Z</kbd> twice.

## Current result
The second paragraph has been removed.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/29401899-44b2d94e-8333-11e7-9ec2-d28a1ecdc240.gif)

**Comment by Mgsy** [comment]
## Steps to reproduce
1. Create the empty paragraph.
2. Press <kbd>Ctrl</kbd> + <kbd>B</kbd>.
3. Type something.
4. Put the caret at the middle of the word.
5. Press <kbd>Enter</kbd>.
6. Press `Undo` 4 times.

## Current result
There is the error in the console.

## Error
```
basic-transformations.js:270 Uncaught TypeError: Cannot read property 'root' of null
    at addTransformationCase (basic-transformations.js:270)
    at Object.transform (transform.js:59)
    at Object.transformDeltaSets (transform.js:261)
    at Document.transformDeltas (document.js:359)
    at UndoCommand._undo (basecommand.js:140)
    at Array.editor.document.enqueueChanges (undocommand.js:40)
    at Document.enqueueChanges (document.js:241)
    at UndoCommand.execute (undocommand.js:39)
    at UndoCommand.on (observablemixin.js:327)
    at UndoCommand.fire (emittermixin.js:281)
```

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/29404319-feaf4664-833a-11e7-8d04-5055d26468b2.gif)

**Comment by Mgsy** [comment]
## Steps to reproduce
1. Put the caret at the middle of some word, i.e. `paragraph`.
2. Press <kbd>Enter</kbd>.
3. Make the following selection:
```
parag{
raph}
```
4. Press <kbd>Delete</kbd>.
5. Press <kbd>Ctrl</kbd> + <kbd>Z</kbd> twice.

## Current result
Undo doesn't merge the word.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/29510602-a7634a02-865c-11e7-8d21-907d38b4c3f8.gif)

**Comment by Mgsy** [comment]
## Type: Redo, selection restoring

### Steps to reproduce
1. Create the paragraph below the block quote.
2. Type something.
3. Put the caret at the beginning of the paragraph.
4. Press <kbd>Backspace</kbd>.
5. Press <kbd>Ctrl</kbd> + <kbd>Z</kbd>.
6. Press <kbd>Ctrl</kbd> + <kbd>Y</kbd>.

### Current result
Block quote was applied to the paragraph instead of moving paragraph to the end of the block quote.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/30317252-deb213a4-97a9-11e7-8ae3-27e04995791d.gif)

**Comment by Reinmar** [comment]
Type: Undo, incorrect data, crash

https://github.com/ckeditor/ckeditor5-engine/issues/1152

**Comment by Mgsy** [comment]
## Type: Redo, selection restoring

### Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Copy two block elements.
3. Create new empty line.
4. Press <kbd>Ctrl</kbd> + <kbd>V</kbd>.
5. Press <kbd>Ctrl</kbd> + <kbd>Z</kbd>.
6. Press <kbd>Ctrl</kbd> + <kbd>Y</kbd>.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31431020-cc3f5080-ae72-11e7-9856-bc3a5fc655a3.gif)

**Comment by Mgsy** [comment]
## Type: Undo, incorrect data

### Steps to reproduce
1. Create new `block quote`.
2. Inside the QB create the list with one nested item.
3. Select whole list.
4. Press <kbd>Delete</kbd>.
5. Press <kbd>Ctrl</kbd> + <kbd>Z</kbd>.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31433400-7c3687f0-ae79-11e7-8088-97f6f1bf8759.gif)

**Comment by Mgsy** [comment]
## Type: Redo, crash

### Steps to reproduce
1. Create new `blockquote` below other block element.
2. Type some word.
3. Split it.
4. Select divided word.
5. Press <kbd>Delete</kbd>.
6. Undo.
7. Redo.
8. Press <kbd>Backspace</kbd>.

### Error
```
ckeditor.js:5 Uncaught o: move-operation-node-into-itself: Trying to move a range of nodes into one of nodes from that range. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#move-operation-node-into-itself.
    at d._execute (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:50554)
    at x.applyOperation (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:246675)
    at n (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:107507)
    at o.move (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:108252)
    at n (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:242104)
    at t.a (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:243111)
    at _.deleteContent (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:222073)
    at _.on (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:29276)
    at _.fire (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:23735)
    at _.(anonymous function) [as deleteContent] (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:29327)
```

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31442894-20aa93b2-ae98-11e7-93e1-dea3c848352c.gif)

**Comment by Mgsy** [comment]
## Type: Redo, crash

### Steps to reproduce
1. Create new `blockquote` below other block element.
2. Type some word.
3. Split it.
4. Select divided word.
5. Press <kbd>Delete</kbd>.
6. Undo.
7. Redo.
8. Press <kbd>Backspace</kbd>.

### Error
```
ckeditor.js:5 Uncaught o: move-operation-node-into-itself: Trying to move a range of nodes into one of nodes from that range. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#move-operation-node-into-itself.
    at d._execute (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:50554)
    at x.applyOperation (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:246675)
    at n (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:107507)
    at o.move (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:108252)
    at n (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:242104)
    at t.a (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:243111)
    at _.deleteContent (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:222073)
    at _.on (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:29276)
    at _.fire (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:23735)
    at _.(anonymous function) [as deleteContent] (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:29327)
```

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31442894-20aa93b2-ae98-11e7-93e1-dea3c848352c.gif)

**Comment by Mgsy** [comment]
## Type: Undo, incorrect data

### Steps to reproduce
1. Put the caret in the middle of some word.
2. Press <kbd>Enter</kbd>.
3. Select divided parts.
4. Press <kbd>Delete</kbd>.
5. Add the `block quote`.
6. Undo twice.

### Current result
Divided word is missing bottom part.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31539304-7ee3213a-b008-11e7-9bc6-c6ade6b904da.gif)

**Comment by Mgsy** [comment]
## Type: Undo, crash

### Steps to reproduce
1. Create the list with one nested item.
2. Create the empty paragraph below the list.
3. Press <kbd>Enter</kbd>.
4. Type something.
5. Put the caret at the empty paragraph and press <kbd>Backspace</kbd> (don't use <kbd>Delete</kbd>).
6. Select part of the first list item and whole second item.
7. Press <kbd>Delete</kbd> twice.
8. Undo twice.

### Current result
Editor crashes.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31540824-00b9fa9a-b00d-11e7-9d19-54c97a35dbd9.gif)

### Error
```
Uncaught o: model-nodelist-offset-out-of-bounds: Given offset cannot be found in the node list. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#model-nodelist-offset-out-of-bounds.
    at i.offsetToIndex (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:93655)
    at l.offsetToIndex (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:13267)
    at d.get index [as index] (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:1937)
    at d.get textNode [as textNode] (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:2013)
    at d.get nodeBefore [as nodeBefore] (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:2196)
    at h.getSelectedElement (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:73188)
    at _updateCaptionVisibility (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:390795)
    at _.listenTo (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:390524)
    at _.fire (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:23714)
    at _.(anonymous function) [as render] (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:29306)
```

**Comment by Mgsy** [comment]
## Type: undo, incorrect data

### Steps to reproduce
1. Type `test`.
2. Put the caret after `t` and press <kbd>Enter</kbd>.
3. Repeat step 2 for every character. You should receive:
```
t
e
s
t
```
4. Delete every character, starting from the last one.
5. Put the caret at the last empty line.
6. Press <kbd>Backspace</kbd> 3 times.
7. Undo until word is restored.

### Current result
Word has been restored, but characters have incorrect position - the result is `tets`, instead of `test`.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31543962-ef49d9ae-b018-11e7-9610-6960ce3a1f52.gif)

**Comment by Mgsy** [comment]
## Type: Undo, incorrect data

### Steps to reproduce
1. Create two paragraphs with some words.
2. Put the caret at the second paragraph.
3. Transform it into the `block quote`.
4. Select the word inside the `block quote`.
5. Press <kbd>Backspace</kbd> 3 times.
6. Undo.

### Current result
Deleted character from the first paragraph has been restored inside the `block quote`.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31546279-e6961d04-b022-11e7-84f5-5d34a62ea819.gif)

**Comment by Mgsy** [comment]
## Type: Undo, crash

### Steps to reproduce
1. Create two paragraphs with some words.
2. Put the caret at the second paragraph.
3. Transform it into the `Heading 1`.
4. Select this word.
5. Press <kbd>Backspace</kbd> 3 times.
6. Undo.

### Current result
Editor crashes.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31547552-0bf7f86a-b028-11e7-8d32-ec4decc6faeb.gif)

**Comment by Mgsy** [comment]
## Type: Undo, crash

### Steps to reproduce
1. Select two block elements.
2. Click on the `block quote` icon.
3. Press <kbd>Delete</kbd>.
4. Click on the `block quote` icon.
5. Undo twice.

### Current result
Editor crashes

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31549084-57e0c46e-b02d-11e7-8f6f-f3c5b6a5cfd7.gif)

### Error
```
ckeditor.js:5 Uncaught o: move-operation-position-invalid: Source position or target position is invalid. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#move-operation-position-invalid.
    at i._execute (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:49878)
    at x.applyOperation (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:246824)
    at o._undo (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:202841)
    at Array.editor.document.enqueueChanges (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:336109)
    at x.enqueueChanges (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:247377)
    at o.execute (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:336076)
    at on (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:29255)
    at o.fire (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:23714)
    at o.(anonymous function) [as execute] (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:29306)
    at o.execute (http://192.168.20.68:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:75:220184)
```

**Comment by Mgsy** [comment]
## Type: Undo, incorrect data

### Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the caret at the end of the `Heading 1`.
3. Press <kbd>Enter</kbd>.
4. Press <kbd>Backspace</kbd>.
5. Delete the word character by character with <kbd>Backspace</kbd>.
6. Undo.

### Current result
First character of the word has been moved to the new line.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31601148-202b2374-b259-11e7-870f-3362e8756515.gif)

**Comment by Mgsy** [comment]
## Type: Undo, crash

### Steps to reproduce
1. Create 3 paragraphs with some text.
2. Select first paragraph and press <kbd>Delete</kbd> twice.
3. Select first remained paragraph and part of the second one and press <kbd>Delete</kbd>.
4. Transform remained paragraph into the list.
5. Undo 3 times.

### Current result
Editor crashes.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31611629-268e6b62-b27d-11e7-88fb-4fd07266408f.gif)

### Error
```
ckeditorerror.js:46 Uncaught CKEditorError: model-position-path-incorrect: Position path must be an array with at least one item. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#model-position-path-incorrect.
 {"path":[]}
    at new Position (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:237:10)
    at addTransformationCase (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:47295:24)
    at Object.transform (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:31648:23)
    at Object.transformDeltaSets (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:31851:34)
    at Document.transformDeltas (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:42588:77)
    at UndoCommand._undo (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:36858:37)
    at Array.editor.document.enqueueChanges (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:55081:30)
    at Document.enqueueChanges (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:42470:30)
    at UndoCommand.execute (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:55080:24)
    at UndoCommand.on (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:5873:32)
```

**Comment by Mgsy** [comment]
## Type: Undo, incorrect data

### Steps to reproduce
1. Create 3 paragraphs with some text.
2. Select first paragraph and press <kbd>Delete</kbd> twice.
3. Select remained paragraphs.
4. Press <kbd>Delete</kbd>.
5. Undo twice.

### Current result
The word from the second paragraph has been moved to the third paragraph.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31614840-f6b81888-b287-11e7-8cdb-60f7825d6e19.gif)

**Comment by Mgsy** [comment]
## Type: Undo, selection restoring, incorrect data

### Steps to reproduce
1. Create two paragraphs with some words.
2. Put the caret inside the word from the second paragraph.
3. Press <kbd>Backspace</kbd> twice.
4. Put the caret at the end of the first paragraph.
5. Press <kbd>Delete</kbd>.
6. Repeat step 4.
7. Press and hold <kbd>Backspace</kbd> to delete whole word.
8. Undo 3 times.

### Current result
Characters deleted in step 3 appeared in the first paragraph.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31653324-7e283f7e-b322-11e7-972f-34f1554ef31f.gif)

**Comment by scofalik** [comment]
I have a feeling that many new errors connected with Undo are regressions after a change in `deleteContents` we merged very recently. I am sure that at least one of them is, as I tested it. This means that we will have to solve this in OT, or revert the change.

**Comment by Reinmar** [comment]
Could you report this in the engine and check it there?

**Comment by Mgsy** [comment]
## Type: Undo, crash

### Steps to reproduce
1. Copy the image to the clipboard.
2. Create two paragraphs with some words.
3. Put the caret at the end of the first paragraph and press <kbd>Delete</kbd> to merge with second one.
4. Select whole paragraph and press <kbd>Delete</kbd>.
5. Paste the image.
6. Change its alignment to `side` / `full width`.
7. Undo 4 times.

### Current result
Editor crashes

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31706893-cd582df2-b3ea-11e7-894c-1fc73edc75ba.gif)

### Error
```
ckeditorerror.js:46 Uncaught CKEditorError: model-position-path-incorrect: Position path must be an array with at least one item. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#model-position-path-incorrect.
 {"path":[]}
    at new Position (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:237:10)
    at addTransformationCase (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:47298:24)
    at Object.transform (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:31651:23)
    at Object.transformDeltaSets (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:31854:34)
    at Document.transformDeltas (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:42470:77)
    at UndoCommand._undo (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:36861:37)
    at Array.editor.document.enqueueChanges (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:55098:30)
    at Document.enqueueChanges (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:42352:30)
    at UndoCommand.execute (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:55097:24)
    at UndoCommand.on (http://192.168.20.68:8125/ckeditor5-core/tests/manual/article.js:5873:32)
```

**Comment by scofalik** [comment]
## Type: Redo, incorrect data

### Steps to reproduce
1. Create content with three `<p>`s.
2. Select whole content and wrap it in blockquote.
3. Put caret in the middle paragraph.
4. Unwrap it from blockquote.
5. Undo, undo.
6. Redo, redo

### Current result
The unwrapped paragraph is moved to the beginning.

### GIF
![oct-27-2017 15-22-35](https://user-images.githubusercontent.com/1502228/32105938-8a08c326-bb2a-11e7-8551-48fbcd6dde05.gif)

**Comment by Mgsy** [comment]
## Type: Redo, selection restoring, incorrect data
### Steps to reproduce
1. Create three block quotes.
2. Select them.
3. Press <kbd>Delete</kbd>.
4. Undo until they disappear.
5. Redo to restore removed block quotes.

### Current result
Block quotes have been restored in reversed order.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/32217170-766442e6-be27-11e7-8e6f-c7220d6a2d9d.gif)

**Comment by Mgsy** [comment]
## Type: Undo, incorrect data
### Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the caret after `H` at `Heading 1`.
3. Split the word with <kbd>Enter</kbd>.
4. Put the caret at the end of the second divided part.
5. Press <kbd>Backspace</kbd>.
6. Repeat step 4 and 5 for the first divided part.
7. Put the caret at the end of the second divided part.
8. Press <kbd>Backspace</kbd> 8 times.
9. Undo until word is restored.

### Current result
Word has been restored incorrectly.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/32218199-7abab192-be2a-11e7-91d0-bb67f0a6f84c.gif)

**Comment by Mgsy** [comment]
### Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Start the selection from the end of the `OL List item 2` and drag it to the first `Quote`.
3. Apply the `block quote`.
4. Undo.

### Current result
Whole `block quote` has disappeared.

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/34669727-69504834-f473-11e7-8258-e1784ca9a4ff.gif)

**Comment by Mgsy** [comment]
## Type: Undo, crash
### Steps to reproduce
1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Delete whole content.
3. Create the block quote with two empty paragraphs.
4. Put the caret at the first paragraph.
5. Click on the `block quote` icon.
6. Undo.

### Current result
Editor crashes

### Error
```
mapper.js:398 Uncaught TypeError: Cannot read property 'is' of undefined
    at Mapper._findPositionIn (mapper.js:398)
    at Mapper.on (mapper.js:73)
    at Mapper.fire (emittermixin.js:269)
    at Mapper.toViewPosition (mapper.js:237)
    at ModelConversionDispatcher.<anonymous> (model-selection-to-view-converters.js:86)
    at ModelConversionDispatcher.fire (emittermixin.js:269)
    at ModelConversionDispatcher.convertSelection (modelconversiondispatcher.js:253)
    at Model.EditingController.listenTo (editingcontroller.js:126)
    at Model.fire (emittermixin.js:269)
    at Model._runPendingChanges (model.js:209)
```

### Notes
Here is the first bad commit - https://github.com/ckeditor/ckeditor5-image/commit/7a1ab67059127a9b8759d5a106738907ae14c84d

### GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/34671684-c9a0e3c6-f47b-11e7-9ed1-561f6ba32827.gif)

**Comment by scofalik** [comment]
## Type: Undo, incorrect data
### Steps to reproduce
1. Open http://localhost:8125/ckeditor5-core/tests/manual/article.html
2. Place caret at the end of the second line.
3. Press and keep backspace to delete text up to the beginning of the document.
4. Press Undo.

### Current result
The content is different than at the beginning

### Expected result
After undo the content is same as before deleting the text
